#!/usr/bin/env Rscript
options(warn = -1)

# Help Document
help_document = function() {
    cat("
    Description:
    This script compares MD5 checksums from two files to verify the integrity of files transferred or stored in different locations.

    Usage:
    script.R [options] <old_md5_file> <new_md5_file> <output_file>

    Options:
    -h, --help       Show this help message and exit.

    Arguments:
    old_md5_file     Path to the file containing original MD5 checksums.
    new_md5_file     Path to the file containing new MD5 checksums to compare against the original.
    output_file      Path to the file where the comparison result will be saved. The result includes the filename and a consistency status.

    Output:
    The output is a tab-separated values file with columns indicating the filename, old and new MD5 checksums, and a consistency flag (TRUE if checksums match, FALSE otherwise).

    Example:
    script.R old_checksums.md5 new_checksums.md5 comparison_result.tsv

    Note:
    Both MD5 checksum files should be in the format generated by 'md5sum' command, i.e., '<checksum>  <file path>'.
    ")
}

# Parse command line arguments
args = commandArgs(trailingOnly = TRUE)

# Check for help request or no arguments
if ('-h' %in% args || '--help' %in% args || length(args) == 0) {
    help_document()
    quit(status = 0)
}

# Ensure there are exactly 3 arguments provided
if (length(args) != 3) {
    cat("Error: Incorrect number of arguments supplied.\n\n")
    help_document()
    quit(status = 1)
}

# Proceed with the script if not help request
old_md5_file = args[1]
new_md5_file = args[2]
output_file = args[3]

suppressPackageStartupMessages(library(tidyverse))

# Read and process the old MD5 file
df_old_md5 = read_delim(old_md5_file, col_names = F, show_col_types = FALSE) %>%
                select(-X2) %>%
                mutate(X3 = basename(X3)) %>%
                rename_with(~paste("old", .x, sep = "_"))

# Read and process the new MD5 file
df_new_md5 = read_delim(new_md5_file, col_names = F, show_col_types = FALSE) %>%
                select(-X2) %>%
                mutate(X3 = basename(X3)) %>%
                rename_with(~paste("new", .x, sep = "_"))

# Compare the old and new MD5, and write the result
df_compare_res = df_old_md5 %>%
                    left_join(df_new_md5, by = c("old_X3" = "new_X3")) %>%
                    mutate(consistent = ifelse(old_X1 == new_X1, TRUE, FALSE))

df_compare_res %>% write_tsv(file = output_file)

print("Comparison finished.")
