#!/usr/bin/env Rscript
options(warn = -1)

# Help Document
help_document = function() {
    cat("
    Description:
    This script compares MD5 checksums from two files to verify the integrity of files transferred or stored in different locations.

    Usage:
    script.R [options] <reference_md5_file> <query_md5_file> <output_file>

    Options:
    -h, --help       Show this help message and exit.

    Arguments:
    reference_md5_file   Path to the file containing the reference MD5 checksums.
    query_md5_file       Path to the file containing the query MD5 checksums to compare against the reference.
    output_file          Path to the file where the comparison result will be saved. The result includes the filename and a consistency status.

    Output:
    The output is a tab-separated values file with columns indicating the filename, reference and query MD5 checksums, and a consistency flag (TRUE if checksums match, FALSE otherwise).

    Example:
    script.R reference_checksums.md5 query_checksums.md5 comparison_result.tsv

    Note:
    Both MD5 checksum files should be in the format generated by 'md5sum' command, i.e., '<checksum>  <file path>'.
    ")
}

# Parse command line arguments
args = commandArgs(trailingOnly = TRUE)

# Check for help request or no arguments
if ('-h' %in% args || '--help' %in% args || length(args) == 0) {
    help_document()
    quit(status = 0)
}

# Ensure there are exactly 3 arguments provided
if (length(args) != 3) {
    cat("Error: Incorrect number of arguments supplied.\n\n")
    help_document()
    quit(status = 1)
}

# Proceed with the script if not help request
reference_md5_file = args[1]
query_md5_file = args[2]
output_file = args[3]

suppressPackageStartupMessages(library(tidyverse))

# Read and process the reference MD5 file
read_func_wrap = function(file_path,marker="default"){
    df_temp = read_delim(file_path,col_names = F, show_col_types = FALSE) %>%
                    select(-X2) %>%
                    mutate(basename = basename(X3)) %>%
                    select(-X3) %>%
                    setNames(c("md5sum","basename"))%>%
                    rename_with(~paste(marker, .x, sep = "_"))
    return(df_temp)
}


df_reference_md5 = read_func_wrap(reference_md5_file,"reference")

# Read and process the query MD5 file
df_query_md5 = read_func_wrap(query_md5_file,"query")

# Compare the reference and query MD5, and write the result
df_compare_res = df_reference_md5 %>%
                    full_join(df_query_md5, by = c("reference_basename" = "query_basename"), keep = TRUE) %>%
                    mutate(consistent = ifelse(reference_md5sum == query_md5sum, TRUE, FALSE))

df_compare_res %>% write_tsv(file = output_file)

print("Comparison finished.")
